### ISSUE TITLE
为什么img设置max-width: 100%会失真啊？

### ISSUE THREAD

**Issue by cooper1x** [Archeb/LightWhite#6]
我从这个网站过来的，看到你的主题很漂亮。
https://elatisy.top/archives/69/
但是有个问题，图片不支持点击放大，默认的大小很影响美观，所以我加了一行max-width: 100%。
但是这样图片缩小反而不清晰了，只有原始尺寸才是清晰的，这是为什么呢？

**Comment by Archeb** [comment]
我觉得这个是浏览器渲染的问题...我这边有时候也会有这种奇怪的现象...头像的缩放也是
